spring.application.name=veebipood

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://dpg-d7ca82bbc2fs73eqtf5g-a.virginia-postgres.render.com/veebipood_andmebaas
spring.datasource.username=veebipood_user
spring.datasource.password=xu9TsQ9ybTAlVIXUTQExqVoivThKL3va